apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: backend-ses-echo
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: Echo API da SES
  privateBaseURL: 'https://echo-api.3scale.net/ses'
  systemName: backend-ses-echo
